name: Build and Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - deploy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=long
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/deploy' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Wait for Registry sync
        run: sleep 15

      - name: Trigger Easypanel Deploy Webhook
        if: github.ref == 'refs/heads/deploy'
        run: curl -X GET --max-time 30 --retry 3 "https://ep.maisvendaspro.com.br/api/deploy/a139e846d0971b75db8e16d5afc7aaf472511c6a41c98ff6"

